In [1]:
import pandas as pd

### FIFA RANK
- F_Rank,F_Point,F_Rd,F_Pd

In [2]:
data = {
    "Nation": [
        "미국","멕시코","캐나다","아르헨티나","브라질","잉글랜드","프랑스","독일","일본","포르투갈",
        "대한민국","스페인","호주","코스타리카","크로아티아","스위스","우루과이","벨기에","카메룬","덴마크",
        "에콰도르","가나","이란","이탈리아","네덜란드","나이지리아","폴란드","사우디아라비아","튀니지","코트디부아르",
        "파라과이","러시아","세네갈","세르비아","스웨덴","알제리","칠레","콜롬비아","그리스","온두라스",
        "모로코","슬로베니아","남아프리카공화국","카타르","이집트","체코","앙골라","북한","노르웨이","오스트리아"
    ],
    "Eng_Nation": [
        "United States","Mexico","Canada","Argentina","Brazil","England","France","Germany","Japan","Portugal",
        "South Korea","Spain","Australia","Costa Rica","Croatia","Switzerland","Uruguay","Belgium","Cameroon","Denmark",
        "Ecuador","Ghana","Iran","Italy","Netherlands","Nigeria","Poland","Saudi Arabia","Tunisia","Ivory Coast",
        "Paraguay","Russia","Senegal","Serbia","Sweden","Algeria","Chile","Colombia","Greece","Honduras",
        "Morocco","Slovenia","South Africa","Qatar","Egypt","Czech Republic","Angola","North Korea","Norway","Austria"
    ]
}

input_df = pd.DataFrame(data)
input_df.head()

  Nation     Eng_Nation
0     미국  United States
1    멕시코         Mexico
2    캐나다         Canada
3  아르헨티나      Argentina
4    브라질         Brazil

In [3]:
fifa_rank_df = pd.read_csv("./../data/source data/avg_rank_points.csv")
fifa_rank_df.head()

          team    rank  wc_year  total_points  rank_diff  points_diff
0  Afghanistan  198.33     2006         54.33        NaN          NaN
1  Afghanistan  188.00     2010         29.33     -10.33       -25.00
2  Afghanistan  159.33     2014        139.67     -28.67       110.34
3  Afghanistan  145.67     2018        191.33     -13.66        51.66
4  Afghanistan  143.33     2022       1077.11      -2.34       885.78

In [4]:
fifa_rank_df = fifa_rank_df[fifa_rank_df['wc_year'] == 2026]
fifa_rank_df

                team    rank  wc_year  total_points  rank_diff  points_diff
5        Afghanistan  157.00     2026       1015.83      13.67       -61.28
12           Albania   65.00     2026       1378.68      -0.33        14.77
19           Algeria   37.67     2026       1498.76       3.34        16.55
26    American Samoa  188.00     2026        883.17       3.33      -100.45
33           Andorra  165.33     2026        986.99      27.33       -88.51
...              ...     ...      ...           ...        ...          ...
1441         Vietnam  108.33     2026       1191.48      12.33       -52.88
1448           Wales   30.67     2026       1522.05       9.67       -23.15
1455           Yemen  155.00     2026       1020.95      14.50       -53.55
1464          Zambia   86.67     2026       1271.81       2.00       -14.25
1471        Zimbabwe  124.67     2026       1135.77      10.67       -32.87

[210 rows x 6 columns]

In [5]:
columns = {
    'team':'Eng_Nation',
    'rank':'F_Rank',
    'wc_year':'Year',
    'total_points':'F_Point',
    'rank_diff':'F_Rd',
    'points_diff':'F_Pd'
}

renamed_df = fifa_rank_df.rename(columns=columns)
fifa_rank_df = pd.DataFrame(renamed_df)
fifa_rank_df

          Eng_Nation  F_Rank  Year  F_Point   F_Rd    F_Pd
5        Afghanistan  157.00  2026  1015.83  13.67  -61.28
12           Albania   65.00  2026  1378.68  -0.33   14.77
19           Algeria   37.67  2026  1498.76   3.34   16.55
26    American Samoa  188.00  2026   883.17   3.33 -100.45
33           Andorra  165.33  2026   986.99  27.33  -88.51
...              ...     ...   ...      ...    ...     ...
1441         Vietnam  108.33  2026  1191.48  12.33  -52.88
1448           Wales   30.67  2026  1522.05   9.67  -23.15
1455           Yemen  155.00  2026  1020.95  14.50  -53.55
1464          Zambia   86.67  2026  1271.81   2.00  -14.25
1471        Zimbabwe  124.67  2026  1135.77  10.67  -32.87

[210 rows x 6 columns]

In [6]:
nation_map = {
    'Korea DPR':'South Korea',
    'Korea Republic':'North Korea',
    'USA':'United States',
    'IR Iran':'Iran',
    "Côte d'Ivoire":'Ivory Coast'
}

fifa_rank_df['Eng_Nation'] = fifa_rank_df['Eng_Nation'].str.strip().replace(nation_map)
print(fifa_rank_df['Eng_Nation'].unique())
print(fifa_rank_df['Eng_Nation'].isnull().sum())

['Afghanistan' 'Albania' 'Algeria' 'American Samoa' 'Andorra' 'Angola'
 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan'
 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'British Virgin Islands' 'Brunei Darussalam' 'Bulgaria' 'Burkina Faso'
 'Burundi' 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada' 'Cayman Islands'
 'Central African Republic' 'Chad' 'Chile' 'China PR' 'Chinese Taipei'
 'Colombia' 'Comoros' 'Congo' 'Congo DR' 'Cook Islands' 'Costa Rica'
 'Croatia' 'Cuba' 'Curaçao' 'Cyprus' 'Czechia' 'Ivory Coast' 'Denmark'
 'Djibouti' 'Dominica' 'Dominican Republic' 'Ecuador' 'Egypt'
 'El Salvador' 'England' 'Equatorial Guinea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Faroe Islands' 'Fiji' 'Finland' 'France' 'Gabon' 'Georgia'
 'Germany' 'Ghana' 'Gibraltar' 'Greece' 'Grenada' 'Guam' 'Guatemala'
 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Honduras' 'Hong Kong'
 'Hungary' 'Iran' 'Iceland' 'India' 'Indonesia' 'Iraq' 'Israel' 'Italy'
 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan' 'Kenya' 'South Korea'
 'North Korea' 'Kosovo' 'Kuwait' 'Kyrgyz Republic' 'Laos' 'Latvia'
 'Lebanon' 'Lesotho' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania'
 'Luxembourg' 'Macau' 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali'
 'Malta' 'Mauritania' 'Mauritius' 'Mexico' 'Moldova' 'Mongolia'
 'Montenegro' 'Montserrat' 'Morocco' 'Mozambique' 'Myanmar' 'Namibia'
 'Nepal' 'Netherlands' 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger'
 'Nigeria' 'North Macedonia' 'Northern Ireland' 'Norway' 'Oman' 'Pakistan'
 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines'
 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Republic of Ireland' 'Romania'
 'Russia' 'Rwanda' 'Samoa' 'San Marino' 'Saudi Arabia' 'Scotland'
 'Senegal' 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia'
 'Slovenia' 'Solomon Islands' 'Somalia' 'South Africa' 'South Sudan'
 'Spain' 'Sri Lanka' 'St Kitts and Nevis' 'St Lucia'
 'St Vincent and the Grenadines' 'Sudan' 'Suriname' 'Sweden' 'Switzerland'
 'Syria' 'São Tomé and Príncipe' 'Tahiti' 'Tajikistan' 'Tanzania'
 'Thailand' 'The Gambia' 'Timor-Leste' 'Togo' 'Tonga'
 'Trinidad and Tobago' 'Tunisia' 'Turkmenistan' 'Turks and Caicos Islands'
 'Türkiye' 'US Virgin Islands' 'United States' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'Uruguay' 'Uzbekistan' 'Vanuatu' 'Venezuela'
 'Vietnam' 'Wales' 'Yemen' 'Zambia' 'Zimbabwe']
0

In [7]:
merged_df = pd.merge(input_df, fifa_rank_df, on=['Eng_Nation'], how='left')
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Nation      50 non-null     object
 1   Eng_Nation  50 non-null     object
 2   F_Rank      49 non-null     float64
 3   Year        49 non-null     float64
 4   F_Point     49 non-null     float64
 5   F_Rd        49 non-null     float64
 6   F_Pd        49 non-null     float64
dtypes: float64(5), object(2)
memory usage: 2.9+ KB

In [8]:
merged_df[merged_df.isna().any(axis=1)]

   Nation      Eng_Nation  F_Rank  Year  F_Point  F_Rd  F_Pd
45     체코  Czech Republic     NaN   NaN      NaN   NaN   NaN

In [9]:
merged_df.to_csv("./../data/result data/input_data.csv", index=False)
merged_df.head()

  Nation     Eng_Nation  F_Rank    Year  F_Point   F_Rd    F_Pd
0     미국  United States   15.00  2026.0  1660.31  -4.00   83.61
1    멕시코         Mexico   14.33  2026.0  1661.83   3.66   31.77
2    캐나다         Canada   36.00  2026.0  1506.31 -30.33  149.57
3  아르헨티나      Argentina    1.67  2026.0  1870.25  -6.66  216.15
4    브라질         Brazil    4.67  2026.0  1790.41   2.00   42.83

In [10]:
# fifa_rank_df = fifa_rank_df.drop(columns=['Year'])
# fifa_rank_df