In [316]:
import pandas as pd

### 2026 월드컵 이전 3년 평균 FIFA 랭킹 데이터
- F_Rank,F_Point,F_Rd,F_Pd

In [317]:
data = {
    "Nation": [
        "미국","멕시코","캐나다","아르헨티나","브라질","잉글랜드","프랑스","독일","일본","포르투갈",
        "대한민국","스페인","호주","코스타리카","크로아티아","스위스","우루과이","벨기에","카메룬","덴마크",
        "에콰도르","가나","이란","이탈리아","네덜란드","나이지리아","폴란드","사우디아라비아","튀니지","코트디부아르",
        "파라과이","러시아","세네갈","세르비아","스웨덴","알제리","칠레","콜롬비아","그리스","온두라스",
        "모로코","슬로베니아","남아프리카공화국","카타르","이집트","체코","앙골라","북한","노르웨이","오스트리아"
    ],
    "Eng_Nation": [
        "United States","Mexico","Canada","Argentina","Brazil","England","France","Germany","Japan","Portugal",
        "South Korea","Spain","Australia","Costa Rica","Croatia","Switzerland","Uruguay","Belgium","Cameroon","Denmark",
        "Ecuador","Ghana","Iran","Italy","Netherlands","Nigeria","Poland","Saudi Arabia","Tunisia","Ivory Coast",
        "Paraguay","Russia","Senegal","Serbia","Sweden","Algeria","Chile","Colombia","Greece","Honduras",
        "Morocco","Slovenia","South Africa","Qatar","Egypt","Czechia","Angola","North Korea","Norway","Austria"
    ]
}

input_df = pd.DataFrame(data)
input_df.head()

  Nation     Eng_Nation
0     미국  United States
1    멕시코         Mexico
2    캐나다         Canada
3  아르헨티나      Argentina
4    브라질         Brazil

In [318]:
fifa_rank_df = pd.read_csv("./../data/source data/avg_rank_points.csv")
fifa_rank_df.head()

          team    rank  wc_year  total_points  rank_diff  points_diff
0  Afghanistan  198.33     2006         54.33        NaN          NaN
1  Afghanistan  188.00     2010         29.33     -10.33       -25.00
2  Afghanistan  159.33     2014        139.67     -28.67       110.34
3  Afghanistan  145.67     2018        191.33     -13.66        51.66
4  Afghanistan  143.33     2022       1077.11      -2.34       885.78

In [319]:
fifa_rank_df = fifa_rank_df[fifa_rank_df['wc_year'] == 2026]
fifa_rank_df

                team    rank  wc_year  total_points  rank_diff  points_diff
5        Afghanistan  157.00     2026       1015.83      13.67       -61.28
12           Albania   65.00     2026       1378.68      -0.33        14.77
19           Algeria   37.67     2026       1498.76       3.34        16.55
26    American Samoa  188.00     2026        883.17       3.33      -100.45
33           Andorra  165.33     2026        986.99      27.33       -88.51
...              ...     ...      ...           ...        ...          ...
1441         Vietnam  108.33     2026       1191.48      12.33       -52.88
1448           Wales   30.67     2026       1522.05       9.67       -23.15
1455           Yemen  155.00     2026       1020.95      14.50       -53.55
1464          Zambia   86.67     2026       1271.81       2.00       -14.25
1471        Zimbabwe  124.67     2026       1135.77      10.67       -32.87

[210 rows x 6 columns]

In [320]:
fifa_rank_df[fifa_rank_df['team'] == 'South Korea']

Empty DataFrame
Columns: [team, rank, wc_year, total_points, rank_diff, points_diff]
Index: []

In [321]:
columns = {
    'team':'Eng_Nation',
    'rank':'F_Rank',
    'wc_year':'Year',
    'total_points':'F_Point',
    'rank_diff':'F_Rd',
    'points_diff':'F_Pd'
}

renamed_df = fifa_rank_df.rename(columns=columns)
fifa_rank_df = pd.DataFrame(renamed_df)
fifa_rank_df

          Eng_Nation  F_Rank  Year  F_Point   F_Rd    F_Pd
5        Afghanistan  157.00  2026  1015.83  13.67  -61.28
12           Albania   65.00  2026  1378.68  -0.33   14.77
19           Algeria   37.67  2026  1498.76   3.34   16.55
26    American Samoa  188.00  2026   883.17   3.33 -100.45
33           Andorra  165.33  2026   986.99  27.33  -88.51
...              ...     ...   ...      ...    ...     ...
1441         Vietnam  108.33  2026  1191.48  12.33  -52.88
1448           Wales   30.67  2026  1522.05   9.67  -23.15
1455           Yemen  155.00  2026  1020.95  14.50  -53.55
1464          Zambia   86.67  2026  1271.81   2.00  -14.25
1471        Zimbabwe  124.67  2026  1135.77  10.67  -32.87

[210 rows x 6 columns]

In [322]:
nation_map = {
    'Korea Republic':'South Korea',
    'Korea DPR':'North Korea',
    'USA':'United States',
    'IR Iran':'Iran',
    "Côte d'Ivoire":'Ivory Coast'
}

fifa_rank_df['Eng_Nation'] = fifa_rank_df['Eng_Nation'].str.strip().replace(nation_map)
print(fifa_rank_df['Eng_Nation'].unique())
print(fifa_rank_df['Eng_Nation'].isnull().sum())

['Afghanistan' 'Albania' 'Algeria' 'American Samoa' 'Andorra' 'Angola'
 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan'
 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'British Virgin Islands' 'Brunei Darussalam' 'Bulgaria' 'Burkina Faso'
 'Burundi' 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada' 'Cayman Islands'
 'Central African Republic' 'Chad' 'Chile' 'China PR' 'Chinese Taipei'
 'Colombia' 'Comoros' 'Congo' 'Congo DR' 'Cook Islands' 'Costa Rica'
 'Croatia' 'Cuba' 'Curaçao' 'Cyprus' 'Czechia' 'Ivory Coast' 'Denmark'
 'Djibouti' 'Dominica' 'Dominican Republic' 'Ecuador' 'Egypt'
 'El Salvador' 'England' 'Equatorial Guinea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Faroe Islands' 'Fiji' 'Finland' 'France' 'Gabon' 'Georgia'
 'Germany' 'Ghana' 'Gibraltar' 'Greece' 'Grenada' 'Guam' 'Guatemala'
 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Honduras' 'Hong Kong'
 'Hungary' 'Iran' 'Iceland' 'India' 'Indonesia' 'Iraq' 'Israel' 'Italy'
 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan' 'Kenya' 'North Korea'
 'South Korea' 'Kosovo' 'Kuwait' 'Kyrgyz Republic' 'Laos' 'Latvia'
 'Lebanon' 'Lesotho' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania'
 'Luxembourg' 'Macau' 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali'
 'Malta' 'Mauritania' 'Mauritius' 'Mexico' 'Moldova' 'Mongolia'
 'Montenegro' 'Montserrat' 'Morocco' 'Mozambique' 'Myanmar' 'Namibia'
 'Nepal' 'Netherlands' 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger'
 'Nigeria' 'North Macedonia' 'Northern Ireland' 'Norway' 'Oman' 'Pakistan'
 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines'
 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Republic of Ireland' 'Romania'
 'Russia' 'Rwanda' 'Samoa' 'San Marino' 'Saudi Arabia' 'Scotland'
 'Senegal' 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia'
 'Slovenia' 'Solomon Islands' 'Somalia' 'South Africa' 'South Sudan'
 'Spain' 'Sri Lanka' 'St Kitts and Nevis' 'St Lucia'
 'St Vincent and the Grenadines' 'Sudan' 'Suriname' 'Sweden' 'Switzerland'
 'Syria' 'São Tomé and Príncipe' 'Tahiti' 'Tajikistan' 'Tanzania'
 'Thailand' 'The Gambia' 'Timor-Leste' 'Togo' 'Tonga'
 'Trinidad and Tobago' 'Tunisia' 'Turkmenistan' 'Turks and Caicos Islands'
 'Türkiye' 'US Virgin Islands' 'United States' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'Uruguay' 'Uzbekistan' 'Vanuatu' 'Venezuela'
 'Vietnam' 'Wales' 'Yemen' 'Zambia' 'Zimbabwe']
0

In [323]:
fifa_rank_df[fifa_rank_df['Eng_Nation'] == 'South Korea']

      Eng_Nation  F_Rank  Year  F_Point   F_Rd   F_Pd
717  South Korea    24.0  2026  1566.27 -13.33  95.13

In [324]:
merged_df = pd.merge(input_df, fifa_rank_df, on=['Eng_Nation'], how='left')
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Nation      50 non-null     object
 1   Eng_Nation  50 non-null     object
 2   F_Rank      50 non-null     float64
 3   Year        50 non-null     int64
 4   F_Point     50 non-null     float64
 5   F_Rd        49 non-null     float64
 6   F_Pd        49 non-null     float64
dtypes: float64(4), int64(1), object(2)
memory usage: 2.9+ KB

In [325]:
merged_df[merged_df.isna().any(axis=1)]

   Nation Eng_Nation  F_Rank  Year  F_Point  F_Rd  F_Pd
45     체코    Czechia   40.67  2026  1491.31   NaN   NaN

In [326]:
merged_df.to_csv("./../data/result data/input_data.csv", index=False)
merged_df.head()

  Nation     Eng_Nation  F_Rank  Year  F_Point   F_Rd    F_Pd
0     미국  United States   15.00  2026  1660.31  -4.00   83.61
1    멕시코         Mexico   14.33  2026  1661.83   3.66   31.77
2    캐나다         Canada   36.00  2026  1506.31 -30.33  149.57
3  아르헨티나      Argentina    1.67  2026  1870.25  -6.66  216.15
4    브라질         Brazil    4.67  2026  1790.41   2.00   42.83

In [327]:
# fifa_rank_df = fifa_rank_df.drop(columns=['Year'])
# fifa_rank_df

---
### 2026 FIFA 랭킹 데이터

In [328]:
fifa_rank_24_df = pd.read_csv("./../data/source data/fifa_ranking_2024-09-19.csv")
fifa_rank_24_df.head()

,Rank,Change,Team,Total_Points,Previous_Points,PlusMinus,Matches,Update_Date
0,1,NaN,Argentina,1889.02,1901.48,-12.46,L W,2024-09-19
1,2,NaN,France,1851.92,1854.91,-2.99,W L,2024-09-19
2,3,NaN,Spain,1836.42,1835.67,+0.75,W D,2024-09-19
3,4,NaN,England,1817.28,1812.26,+5.02,W W,2024-09-19
4,5,NaN,Brazil,1772.02,1785.61,-13.59,L W,2024-09-19

In [329]:
fifa_rank_25_df = pd.read_csv("./../data/source data/fifa_ranking_2025-09-18.csv")
fifa_rank_25_df.head()

,Rank,Change,Team,Total_Points,Previous_Points,PlusMinus,Matches,Update_Date
0,1,1.0,Spain,1875.37,1867.09,+8.28,W W,2025-09-18
1,2,1.0,France,1870.92,1862.03,+8.89,W W,2025-09-18
2,3,2.0,Argentina,1870.32,1885.36,-15.04,L W,2025-09-18
3,4,NaN,England,1820.44,1813.32,+7.12,W W,2025-09-18
4,5,1.0,Portugal,1779.55,1770.53,+9.02,W W,2025-09-18

In [330]:
fifa_rank_24_df = fifa_rank_24_df[["Team", "Rank", "Total_Points"]]
fifa_rank_25_df = fifa_rank_25_df[["Team", "Rank", "Total_Points"]]
fifa_rank_24_df, fifa_rank_25_df

(                         Team  Rank  Total_Points
 0                   Argentina     1       1889.02
 1                      France     2       1851.92
 2                       Spain     3       1836.42
 3                     England     4       1817.28
 4                      Brazil     5       1772.02
 ..                        ...   ...           ...
 205  Turks and Caicos Islands   206        802.81
 206         US Virgin Islands   207        792.15
 207    British Virgin Islands   208        790.63
 208                  Anguilla   209        782.08
 209                San Marino   210        746.05

 [210 rows x 3 columns],
                          Team  Rank  Total_Points
 0                       Spain     1       1875.37
 1                      France     2       1870.92
 2                   Argentina     3       1870.32
 3                     England     4       1820.44
 4                    Portugal     5       1779.55
 ..                        ...   ...           ...
 202                Seychelles   203        812.32
 203             Liechtenstein   204        808.48
 204                   Bahamas   205        807.36
 205  Turks and Caicos Islands   206        803.98
 206         US Virgin Islands   207        779.71

 [207 rows x 3 columns])

In [331]:
merged_df = fifa_rank_25_df.merge(fifa_rank_24_df[['Team', 'Rank', 'Total_Points']], on='Team', how='left', suffixes=('_25', '_24'))
merged_df['F_Rd'] = merged_df['Rank_25'] - merged_df['Rank_24']
merged_df['F_Pd'] = merged_df['Total_Points_25'] - merged_df['Total_Points_24']
merged_df

,Team,Rank_25,Total_Points_25,Rank_24,Total_Points_24,F_Rd,F_Pd
0,Spain,1,1875.37,3,1836.42,-2,38.95
1,France,2,1870.92,2,1851.92,0,19.00
2,Argentina,3,1870.32,1,1889.02,2,-18.70
3,England,4,1820.44,4,1817.28,0,3.16
4,Portugal,5,1779.55,8,1752.14,-3,27.41
...,...,...,...,...,...,...,...
202,Seychelles,203,812.32,201,831.19,2,-18.87
203,Liechtenstein,204,808.48,203,827.19,1,-18.71
204,Bahamas,205,807.36,205,817.25,0,-9.89
205,Turks and Caicos Islands,206,803.98,206,802.81,0,1.17
206,US Virgin Islands,207,779.71,207,792.15,0,-12.44

In [332]:
merged_df = merged_df[['Team', 'Rank_25', 'Total_Points_25', 'F_Rd', 'F_Pd']]
merged_df

                         Team  Rank_25  Total_Points_25  F_Rd   F_Pd
0                       Spain        1          1875.37    -2  38.95
1                      France        2          1870.92     0  19.00
2                   Argentina        3          1870.32     2 -18.70
3                     England        4          1820.44     0   3.16
4                    Portugal        5          1779.55    -3  27.41
..                        ...      ...              ...   ...    ...
202                Seychelles      203           812.32     2 -18.87
203             Liechtenstein      204           808.48     1 -18.71
204                   Bahamas      205           807.36     0  -9.89
205  Turks and Caicos Islands      206           803.98     0   1.17
206         US Virgin Islands      207           779.71     0 -12.44

[207 rows x 5 columns]

In [333]:
columns = {
    'Team':'Eng_Nation',
    'Rank_25':'F_Rank',
    'Total_Points_25':'F_Point',
}

renamed_df = merged_df.rename(columns=columns)
merged_df = pd.DataFrame(renamed_df)
merged_df

                   Eng_Nation  F_Rank  F_Point  F_Rd   F_Pd
0                       Spain       1  1875.37    -2  38.95
1                      France       2  1870.92     0  19.00
2                   Argentina       3  1870.32     2 -18.70
3                     England       4  1820.44     0   3.16
4                    Portugal       5  1779.55    -3  27.41
..                        ...     ...      ...   ...    ...
202                Seychelles     203   812.32     2 -18.87
203             Liechtenstein     204   808.48     1 -18.71
204                   Bahamas     205   807.36     0  -9.89
205  Turks and Caicos Islands     206   803.98     0   1.17
206         US Virgin Islands     207   779.71     0 -12.44

[207 rows x 5 columns]

In [334]:
merged_df[merged_df['Eng_Nation'] == 'Czechia']

   Eng_Nation  F_Rank  F_Point  F_Rd  F_Pd
38    Czechia      39  1500.29    -7  27.1

In [335]:
nation_map = {
    'Korea Republic':'South Korea',
    'Korea DPR':'North Korea',
    'USA':'United States',
    'IR Iran':'Iran',
    "Côte d'Ivoire":'Ivory Coast'
}

merged_df['Eng_Nation'] = merged_df['Eng_Nation'].str.strip().replace(nation_map)
print(merged_df['Eng_Nation'].unique())
print(merged_df['Eng_Nation'].isnull().sum())

['Spain' 'France' 'Argentina' 'England' 'Portugal' 'Brazil' 'Netherlands'
 'Belgium' 'Croatia' 'Italy' 'Morocco' 'Germany' 'Colombia' 'Mexico'
 'Uruguay' 'United States' 'Switzerland' 'Senegal' 'Japan' 'Denmark'
 'Iran' 'Austria' 'South Korea' 'Ecuador' 'Australia' 'Canada' 'Türkiye'
 'Ukraine' 'Panama' 'Wales' 'Norway' 'Sweden' 'Russia' 'Serbia' 'Egypt'
 'Poland' 'Paraguay' 'Algeria' 'Czechia' 'Greece' 'Hungary' 'Slovakia'
 'Scotland' 'Ivory Coast' 'Nigeria' 'Tunisia' 'Costa Rica' 'Peru'
 'Venezuela' 'Slovenia' 'Romania' 'Cameroon' 'Qatar' 'Uzbekistan'
 'South Africa' 'Mali' 'Chile' 'Iraq' 'Saudi Arabia' 'Congo DR'
 'Republic of Ireland' 'Jordan' 'North Macedonia' 'Burkina Faso'
 'Honduras' 'Albania' 'United Arab Emirates' 'Georgia' 'Jamaica'
 'Cabo Verde' 'Finland' 'Northern Ireland' 'Bosnia and Herzegovina'
 'Iceland' 'Ghana' 'Israel' 'Bolivia' 'Oman' 'Gabon' 'Montenegro' 'Guinea'
 'Uganda' 'New Zealand' 'Curaçao' 'Zambia' 'Bulgaria' 'Haiti' 'Bahrain'
 'Angola' 'El Salvador' 'Kosovo' 'Syria' 'Benin' 'China PR'
 'Equatorial Guinea' 'Luxembourg' 'Mozambique' 'Guatemala' 'Palestine'
 'Belarus' 'Thailand' 'Trinidad and Tobago' 'Armenia' 'Tajikistan'
 'Comoros' 'Kyrgyz Republic' 'Tanzania' 'Madagascar' 'Namibia'
 'Mauritania' 'Kenya' 'Libya' 'Lebanon' 'Vietnam' 'The Gambia' 'Sudan'
 'Niger' 'Kazakhstan' 'Indonesia' 'Togo' 'North Korea' 'Sierra Leone'
 'Malaysia' 'Azerbaijan' 'Zimbabwe' 'Malawi' 'Rwanda' 'Cyprus' 'Estonia'
 'Guinea-Bissau' 'Suriname' 'Nicaragua' 'Congo' 'India' 'Kuwait'
 'Faroe Islands' 'Latvia' 'Turkmenistan' 'Botswana'
 'Central African Republic' 'Burundi' 'Dominican Republic' 'Philippines'
 'Liberia' 'Lithuania' 'Hong Kong' 'Ethiopia' 'Solomon Islands'
 'St Kitts and Nevis' 'New Caledonia' 'Guyana' 'Fiji' 'Lesotho' 'Yemen'
 'Puerto Rico' 'Moldova' 'Tahiti' 'Singapore' 'Eswatini' 'Myanmar'
 'Afghanistan' 'Antigua and Barbuda' 'Vanuatu' 'St Lucia' 'Bermuda'
 'Malta' 'Cuba' 'Grenada' 'South Sudan' 'Papua New Guinea' 'Maldives'
 'St Vincent and the Grenadines' 'Chinese Taipei' 'Andorra' 'Chad' 'Nepal'
 'Barbados' 'Montserrat' 'Mauritius' 'Cambodia' 'Belize' 'Dominica'
 'Brunei Darussalam' 'Bangladesh' 'Laos' 'Bhutan' 'American Samoa'
 'Mongolia' 'Cook Islands' 'Samoa' 'Macau' 'Aruba' 'Djibouti'
 'Timor-Leste' 'São Tomé and Príncipe' 'Cayman Islands' 'Sri Lanka'
 'Tonga' 'Pakistan' 'Gibraltar' 'Somalia' 'Guam' 'Seychelles'
 'Liechtenstein' 'Bahamas' 'Turks and Caicos Islands' 'US Virgin Islands']
0

In [337]:
merged_df = pd.merge(input_df, merged_df, on=['Eng_Nation'], how='left')
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Nation      50 non-null     object
 1   Eng_Nation  50 non-null     object
 2   F_Rank      50 non-null     int64
 3   F_Point     50 non-null     float64
 4   F_Rd        50 non-null     int64
 5   F_Pd        50 non-null     float64
dtypes: float64(2), int64(2), object(2)
memory usage: 2.5+ KB

In [338]:
merged_df[merged_df.isna().any(axis=1)]

Empty DataFrame
Columns: [Nation, Eng_Nation, F_Rank, F_Point, F_Rd, F_Pd]
Index: []

In [339]:
merged_df.to_csv("./../data/result data/annual_input_data.csv", index=False)
merged_df.head()

  Nation     Eng_Nation  F_Rank  F_Point  F_Rd   F_Pd
0     미국  United States      16  1670.04    -2  37.85
1    멕시코         Mexico      14  1688.38    -3  52.72
2    캐나다         Canada      26  1558.04   -12  55.73
3  아르헨티나      Argentina       3  1870.32     2 -18.70
4    브라질         Brazil       6  1761.60     1 -10.42