In [24]:
import pandas as pd
import numpy as np

In [25]:
df = pd.read_csv('../data/result data/merged v5.csv')
df

,년도,팀,영문국가명,예선_승률,예선_골득실률,순위,승점,AvgApps,평균나이,top20소속선수수,...,sprint_speed,gk,passing,defending,rank,total_points,rank_diff,points_diff,attack_index,defense_index
0,2002,브라질,Brazil,0.46,2.352113,1,21,0.26087,26.74,3,...,82.09,31.95,68.95,59.61,1.33,818.33,0.00,0.00,0.141500,-0.070093
1,2002,독일,Germany,0.55,1.817073,2,16,0.21739,28.26,10,...,80.57,37.60,62.88,63.29,8.67,718.33,0.00,0.00,0.031444,0.011481
2,2002,터키,Turkey,0.46,1.457627,3,13,0.00000,28.26,1,...,74.05,30.85,65.18,56.78,33.00,593.33,0.00,0.00,-0.039941,0.015588
3,2002,대한민국,South Korea,0.48,2.216667,4,11,0.43478,27.13,0,...,72.45,32.64,57.66,62.23,42.00,573.00,0.00,0.00,0.040250,0.133021
4,2002,스페인,Spain,0.65,3.227273,5,11,0.26087,27.13,3,...,83.27,35.05,69.80,64.55,5.00,742.33,0.00,0.00,-0.105762,-0.099683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,2022,덴마크,Denmark,0.61,2.446429,28,1,0.46154,27.23,4,...,70.15,17.13,66.37,53.93,13.33,1611.83,-18.00,816.50,NaN,NaN
188,2022,세르비아,Serbia,0.48,1.536232,29,1,0.46154,26.92,0,...,64.15,18.21,64.19,51.35,31.33,1492.66,-18.00,852.99,NaN,NaN
189,2022,웨일스,Wales,0.44,1.233333,30,1,0.00000,26.54,0,...,66.27,17.62,59.62,53.12,21.00,1545.20,10.75,409.70,NaN,NaN
190,2022,캐나다,Canada,0.48,2.296875,31,0,0.00000,27.08,0,...,65.60,16.50,56.82,43.71,66.33,1356.74,-34.00,1018.07,NaN,NaN
191,2022,카타르,Qatar,0.49,1.388889,32,0,0.00000,27.12,0,...,68.68,12.24,57.96,49.69,53.33,1406.28,-34.67,1025.61,NaN,NaN

In [26]:
len(df.columns)

30

In [27]:
new_cols = ['Year', 'Nation', 'Eng_Nation', 'Q_WR', 'Q_GR', 'Wc_Rank', 'Wc_Point',
            'Avg_Apps', 'Avg_Age', 'Avg_Famous', 'FS_0', 'FS_1', 'FS_2', 'FS_3', 'FS_4',
            'FS_5', 'FS_6', 'FS_7', 'FS_8', 'FS_9', 'FS_10', 'FS_11', 'FS_12', 'FS_13',
            'F_Rank', 'F_Point', 'F_Rd', 'F_Pd','ATK_INDEX','DEF_INDEX']
df.columns = new_cols
df

,Year,Nation,Eng_Nation,Q_WR,Q_GR,Wc_Rank,Wc_Point,Avg_Apps,Avg_Age,Avg_Famous,...,FS_10,FS_11,FS_12,FS_13,F_Rank,F_Point,F_Rd,F_Pd,ATK_INDEX,DEF_INDEX
0,2002,브라질,Brazil,0.46,2.352113,1,21,0.26087,26.74,3,...,82.09,31.95,68.95,59.61,1.33,818.33,0.00,0.00,0.141500,-0.070093
1,2002,독일,Germany,0.55,1.817073,2,16,0.21739,28.26,10,...,80.57,37.60,62.88,63.29,8.67,718.33,0.00,0.00,0.031444,0.011481
2,2002,터키,Turkey,0.46,1.457627,3,13,0.00000,28.26,1,...,74.05,30.85,65.18,56.78,33.00,593.33,0.00,0.00,-0.039941,0.015588
3,2002,대한민국,South Korea,0.48,2.216667,4,11,0.43478,27.13,0,...,72.45,32.64,57.66,62.23,42.00,573.00,0.00,0.00,0.040250,0.133021
4,2002,스페인,Spain,0.65,3.227273,5,11,0.26087,27.13,3,...,83.27,35.05,69.80,64.55,5.00,742.33,0.00,0.00,-0.105762,-0.099683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,2022,덴마크,Denmark,0.61,2.446429,28,1,0.46154,27.23,4,...,70.15,17.13,66.37,53.93,13.33,1611.83,-18.00,816.50,NaN,NaN
188,2022,세르비아,Serbia,0.48,1.536232,29,1,0.46154,26.92,0,...,64.15,18.21,64.19,51.35,31.33,1492.66,-18.00,852.99,NaN,NaN
189,2022,웨일스,Wales,0.44,1.233333,30,1,0.00000,26.54,0,...,66.27,17.62,59.62,53.12,21.00,1545.20,10.75,409.70,NaN,NaN
190,2022,캐나다,Canada,0.48,2.296875,31,0,0.00000,27.08,0,...,65.60,16.50,56.82,43.71,66.33,1356.74,-34.00,1018.07,NaN,NaN
191,2022,카타르,Qatar,0.49,1.388889,32,0,0.00000,27.12,0,...,68.68,12.24,57.96,49.69,53.33,1406.28,-34.67,1025.61,NaN,NaN

In [28]:
new_cols = ['Year', 'Nation', 'Eng_Nation', 'Wc_Rank', 'Wc_Point', 'Q_WR', 'Q_GR', 
            'F_Rank', 'F_Point', 'F_Rd', 'F_Pd', 'Avg_Apps', 'Avg_Age', 'Avg_Famous', 'FS_0', 'FS_1', 'FS_2', 'FS_3', 'FS_4',
            'FS_5', 'FS_6', 'FS_7', 'FS_8', 'FS_9', 'FS_10', 'FS_11', 'FS_12', 'FS_13','ATK_INDEX','DEF_INDEX']
df = df[new_cols]
df

,Year,Nation,Eng_Nation,Wc_Rank,Wc_Point,Q_WR,Q_GR,F_Rank,F_Point,F_Rd,...,FS_6,FS_7,FS_8,FS_9,FS_10,FS_11,FS_12,FS_13,ATK_INDEX,DEF_INDEX
0,2002,브라질,Brazil,1,21,0.46,2.352113,1.33,818.33,0.00,...,67.95,75.27,77.05,72.73,82.09,31.95,68.95,59.61,0.141500,-0.070093
1,2002,독일,Germany,2,16,0.55,1.817073,8.67,718.33,0.00,...,63.29,66.38,67.86,72.57,80.57,37.60,62.88,63.29,0.031444,0.011481
2,2002,터키,Turkey,3,13,0.46,1.457627,33.00,593.33,0.00,...,62.65,66.45,69.80,67.05,74.05,30.85,65.18,56.78,-0.039941,0.015588
3,2002,대한민국,South Korea,4,11,0.48,2.216667,42.00,573.00,0.00,...,55.41,65.91,65.50,65.68,72.45,32.64,57.66,62.23,0.040250,0.133021
4,2002,스페인,Spain,5,11,0.65,3.227273,5.00,742.33,0.00,...,69.77,75.50,78.23,78.09,83.27,35.05,69.80,64.55,-0.105762,-0.099683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,2022,덴마크,Denmark,28,1,0.61,2.446429,13.33,1611.83,-18.00,...,68.77,72.19,70.69,67.92,70.15,17.13,66.37,53.93,NaN,NaN
188,2022,세르비아,Serbia,29,1,0.48,1.536232,31.33,1492.66,-18.00,...,62.65,66.19,72.58,69.38,64.15,18.21,64.19,51.35,NaN,NaN
189,2022,웨일스,Wales,30,1,0.44,1.233333,21.00,1545.20,10.75,...,67.38,66.19,63.88,55.19,66.27,17.62,59.62,53.12,NaN,NaN
190,2022,캐나다,Canada,31,0,0.48,2.296875,66.33,1356.74,-34.00,...,66.48,66.48,69.76,60.36,65.60,16.50,56.82,43.71,NaN,NaN
191,2022,카타르,Qatar,32,0,0.49,1.388889,53.33,1406.28,-34.67,...,66.40,65.04,63.64,58.20,68.68,12.24,57.96,49.69,NaN,NaN

In [30]:
len(df.columns)

30

In [31]:
df.to_csv('../data/result data/Final DF.csv',index=False,encoding='utf-8')